### ISSUE TITLE
S3MediaStorage's default save tries to save to local static folder

### ISSUE THREAD

**Issue by 722C** [mirumee/django-offsite-storage#1]
Currently, S3MediaStorage descends from StaticFilesStorage, which means that files are being put into the static folder once the _save function calls up to super.  As far as I can tell, it isn't using anything that is specific to StaticFilesStorage and works with the FileSystemStorage, which defaults to the media directory.  Furthermore, it may make sense to not call super at all, as with the FileSystemStorage, it attempts to save to the media folder instead of just the S3 bucket.

**Comment by bogdal** [comment]
You're right, we save the media files in two places unnecessarily. Thanks for this @722C.
